### ISSUE TITLE
Ошибки при деплое не считаются ошибками

### ISSUE THREAD

**Issue by iakov** [spbu-se/spbu_se_site#58]
Шаг завершается успешно.
https://github.com/spbu-se/spbu_se_site/actions/runs/5438602841/job/15325979286#step:4:66

**Comment by foreverjun** [comment]
Насколько я понимаю при каких то ошибках на сервере, никакой код выхода программы в консоль не отправляется, поэтому я решил сделать healthchecker, который максимум через 15 минут предупредит, если сервер возвращает что-то кроме 200 кода
https://github.com/spbu-se/spbu_se_site/pull/69

**Comment by pmokeev** [comment]
@foreverjun Привет! Кажется, ты не совсем правильно понял проблему, описанную в issue. 

**Исходная проблема:** шаг (джоба) пайплайна деплоя не фейлится при первой возникшей ошибке, а более того, говорит о том, что все успешно (`"✅ Successfully executed commands to all host."`, [link](https://github.com/spbu-se/spbu_se_site/actions/runs/5438602841/job/15325979286#step:4:125)). Кажется, это фиксится параметром `script_stop: true` в конфигурации файла `.github/workflows/deploy_to_server.yml` как-то так:
```
      - name: Run deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script_stop: true           # <------
          script:
```
[Ссылка на документацию](https://github.com/appleboy/ssh-action#stop-script-after-first-failure).

**Какую проблему решил ты** (если таковая и правда была, и у сайта не было других способов алертинга о недоступности): ты добавил проверку на "живучесть" сайта, которая выполняется каждые 15 минут и алертит об этом в телеграм канал. По сути это [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) в Kubernetes (jfyi). Это круто, но не решает изначальную проблему, описанную в issue :)
